server:
  port: ${SERVER_PORT:8081}

calculator:
  url: ${CALCULATOR_URL:http://localhost:8080/calculator}

email:
  base-url: ${EMAIL_BASE_URL:http://localhost:8081}

spring:
  application:
    name: deal

  config:
    import: "optional:file:.env[.properties]"

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/credit_scoring}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    com.creditscoring.deal: DEBUG
    org.zalando.logbook: INFO

logbook:
  format:
    style: json
  include:
    - /**
  obfuscate:
    json-body-fields:
      - firstName
      - lastName
      - middleName
      - passportSeries
      - passportNumber

kafka:
  enabled: true
  topics:
    partitions: 3
    replicas: 1
    names:
      FINISH_REGISTRATION: finish-registration
      CREATE_DOCUMENTS: create-documents
      SEND_DOCUMENTS: send-documents
      SEND_SES: send-ses
      CREDIT_ISSUED: credit-issued
      STATEMENT_DENIED: statement-denied