spring:
  application:
    name: dossier
  config:
    import: "optional:file:.env[.properties]"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: dossier-service
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.creditscoring.dossier.dto.EmailMessage

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_SMTP_USERNAME}
    password: ${GMAIL_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port: 8083

deal:
  url: http://localhost:8081/deal

logging:
  level:
    root: INFO
    com.creditscoring.dossier: DEBUG
    org.zalando.logbook: INFO

logbook:
  format:
    style: json
  include:
    - /**
  obfuscate:
    json-body-fields:
      - firstName
      - lastName
      - middleName
      - passportSeries
      - passportNumber