name: Build & test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v5.2.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build + test + SonarQube analysis
      run: mvn clean verify sonar:sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.7
      
